# Generated by Django 3.2.6 on 2021-08-21 04:43

import coupon.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("discount", models.IntegerField()),
                (
                    "code",
                    models.CharField(
                        default=coupon.models.random_code,
                        max_length=6,
                        unique=True,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupans",
                        to="course.course",
                    ),
                ),
            ],
        ),
    ]
