version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: app/app.dockerfile
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 && flake8"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    volumes:
      - data:/var/lib/mysql
    env_file:
      - db/db.env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    ports:
      - 8080:80

volumes:
  data:
