# Generated by Django 3.2.6 on 2021-08-18 04:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=150)),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_chapter', to='chapter.chapter')),
            ],
        ),
    ]
