# Generated by Django 3.2.6 on 2021-08-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
        ("chapter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="course.course",
            ),
        ),
    ]
